package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private JoinPredicate p;
    private DbIterator child1;
    private DbIterator child2;
    private Tuple child1Tuple;
    
    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
    	return this.p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
    	return this.child1.getTupleDesc().getFieldName(this.p.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
    	return this.child2.getTupleDesc().getFieldName(this.p.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
		return TupleDesc.merge(this.child1.getTupleDesc(), this.child2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        this.child1.open();
        this.child2.open();
        this.child1Tuple = child1.next();
        super.open();
    }

    public void close() {
        super.close();
        this.child1.close();
        this.child2.close();
        this.child1Tuple = null;
    }

    public void rewind() throws DbException, TransactionAbortedException {
        this.child1.rewind();
        this.child2.rewind();
        this.child1Tuple = this.child1.next();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
    	while (this.child1Tuple != null) {
    		while (child2.hasNext()) {
    			Tuple currChild2Tuple = child2.next();
    			if (p.filter(this.child1Tuple, currChild2Tuple)) {
    				TupleDesc resultTD = getTupleDesc();
    				Tuple result = new Tuple(resultTD);
    				Iterator<Field> f1 = this.child1Tuple.fields();
    				Iterator<Field> f2 = currChild2Tuple.fields();
    				int i = 0;
    				while (f1.hasNext()) {
    					result.setField(i, f1.next());
    					i++;
    				}
    				
    				while (f2.hasNext()) {
    					result.setField(i, f2.next());
    					i++;
    				}
    				return result;
    			}
    		}
    		if (this.child1.hasNext()) {
    			this.child1Tuple = this.child1.next();
        		child2.rewind();
    		} else {
    			this.child1Tuple = null;
    		}
    	}
    	return null;
    }

    @Override
    public DbIterator[] getChildren() {
    	return new DbIterator[] { this.child1, this.child2 };
    }

    @Override
    public void setChildren(DbIterator[] children) {
    	if (this.child1 != children[0]) {
    	    this.child1 = children[0];
    	}
    	
    	if (this.child2 != children[1]) {
    		this.child2 = children[1];
    	}
    }
}
